----------------Environment Versions----------------
- Python    : 3.7.3 
- PyTorch   : 1.1.0
- TorchVison: 0.3.0
- GPU_device: True
----------------------------------------------------
Parallel mode was going ...
Model loading was finished ...
After data augmentation, 72773 rows added.
After data augmentation,   0 rows added.
Data loading was finished ...
epoch :  1|30, iter : 200|1138,  loss : 1.0424
epoch :  1|30, iter : 400|1138,  loss : 0.7492
epoch :  1|30, iter : 600|1138,  loss : 0.6036
epoch :  1|30, iter : 800|1138,  loss : 0.5153
epoch :  1|30, iter : 1000|1138,  loss : 0.4542
acc : 0.9578, precision : 0.9150, recall : 0.8327, f1_score : 0.8719
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/lujie/deep_learning/face_occ/end2end_detector/train.py in <module>
    248 
    249     anodetector = AnomalyDetetor(training_args())
--> 250     anodetector.train_runner()

~/lujie/deep_learning/face_occ/end2end_detector/train.py in train_runner(self)
    242         self._data_loader()
    243 
--> 244         self._main_loop()
    245 
    246 

~/lujie/deep_learning/face_occ/end2end_detector/train.py in _main_loop(self)
    204             
    205             start_time = time.time()
--> 206             self._model_train(epoch)
    207             self.model['scheduler'].step()
    208             val_loss, f1_score = self._model_eval()

~/lujie/deep_learning/face_occ/end2end_detector/train.py in _model_train(self, epoch)
    159                 print('epoch : %2d|%2d, iter : %3d|%3d,  loss : %.4f' % \
    160                       (epoch, self.args.end_epoch, idx+1, len(self.data['train_loader']), np.mean(loss_recorder)))
--> 161         self._calculate_acc(gt_occ, gt_hos, gt_img, pred_score, verbose=True)
    162         train_loss = np.mean(loss_recorder)
    163         print('train_loss : %.4f' % train_loss)

~/lujie/deep_learning/face_occ/end2end_detector/train.py in _calculate_acc(self, gt_occ, gt_hos, gt_img, scores, verbose)
    115         print('acc : %.4f, precision : %.4f, recall : %.4f, f1_score : %.4f' % \
    116               (acc, precision, recall, f1_score))
--> 117         embed()
    118         if verbose:
    119             print('%s gt vs. pred %s' % ('-' * 36, '-' * 36))

/opt/conda/lib/python3.7/site-packages/IPython/terminal/embed.py in embed(**kwargs)
    387         frame.f_code.co_filename, frame.f_lineno), **kwargs)
    388     shell(header=header, stack_depth=2, compile_flags=compile_flags,
--> 389         _call_location_id='%s:%s' % (frame.f_code.co_filename, frame.f_lineno))
    390     InteractiveShellEmbed.clear_instance()
    391     #restore previous instance

/opt/conda/lib/python3.7/site-packages/IPython/terminal/embed.py in __call__(self, header, local_ns, module, dummy, stack_depth, global_ns, compile_flags, **kw)
    227         # our call and get the original caller's namespaces.
    228         self.mainloop(local_ns, module, stack_depth=stack_depth,
--> 229                       global_ns=global_ns, compile_flags=compile_flags)
    230 
    231         self.banner2 = self.old_banner2

/opt/conda/lib/python3.7/site-packages/IPython/terminal/embed.py in mainloop(self, local_ns, module, stack_depth, display_banner, global_ns, compile_flags)
    322 
    323         with self.builtin_trap, self.display_trap:
--> 324             self.interact()
    325         
    326         # now, purge out the local namespace of IPython's hidden variables.

/opt/conda/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py in interact(self, display_banner)
    479 
    480             try:
--> 481                 code = self.prompt_for_code()
    482             except EOFError:
    483                 if (not self.confirm_exit) \

/opt/conda/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py in prompt()
    252             def prompt():
    253                 prompt_text = "".join(x[1] for x in self.prompts.in_prompt_tokens())
--> 254                 lines = [input(prompt_text)]
    255                 prompt_continuation = "".join(x[1] for x in self.prompts.continuation_prompt_tokens())
    256                 while self.check_complete('\n'.join(lines))[0] == 'incomplete':

/opt/conda/lib/python3.7/site-packages/IPython/utils/py3compat.py in input(prompt)
    152 # to forward requests to a frontend.
    153 def input(prompt=''):
--> 154     return builtin_mod.input(prompt)
    155 
    156 builtin_mod_name = "builtins"

OSError: [Errno 9] Bad file descriptor
